apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
      - args:
        - bash
        - -c
        - 'if [ ! -f /tmp/update_run.sh ]; then echo "ERROR: Did you forget the update_run.sh
          file that came with this docker-compose.yml file?" && exit 1 ; else /tmp/update_run.sh
          && /etc/confluent/docker/run ; fi'
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@broker:29093
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_JMX_HOSTNAME
          value: localhost
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://localhost:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_LOG_DIRS
          value: /tmp/kraft-combined-logs
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        image: confluentinc/cp-kafka:6.2.0
        imagePullPolicy: ""
        name: broker
        ports:
        - containerPort: 9092
        - containerPort: 9101
        resources: {}
        volumeMounts:
        - mountPath: /tmp/update_run.sh
          name: broker-claim0
      hostname: broker
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: broker-claim0
        persistentVolumeClaim:
          claimName: broker-claim0
status: {}
